import * as React from "react";
import { Link, Section, Text } from "@react-email/components";
import { EmailLayout, styles } from "./layout";

export interface PrPendingApprovalEmailProps {
  prNumber: string;
  vendorName: string;
  purpose: string;
  amountLabel?: string | null;
  downpaymentLabel?: string | null;
  downpaymentPercent?: number | null;
  reviewUrl: string;
}

/**
 * Sent to the admins/superadmins the requester selected when a PR is submitted
 * for approval. Summary + link to the PR detail page where the approver can
 * Approve/Reject. The action lives in-app.
 */
export function PrPendingApprovalEmail({
  prNumber,
  vendorName,
  purpose,
  amountLabel,
  downpaymentLabel,
  downpaymentPercent,
  reviewUrl,
}: PrPendingApprovalEmailProps) {
  return (
    <EmailLayout
      preview={`PR ${prNumber} is pending your approval`}
      footerQuestionText="This is an automated email generated by TVPH ERP. Please do not reply directly to this message."
    >
      <Text style={styles.heading}>Dear Approver,</Text>
      <Text style={styles.paragraph}>
        The Purchase Request for {vendorName} has been submitted for your review
        and approval.
      </Text>
      <Section style={styles.panel}>
        <Text style={styles.meta}>PR Number: {prNumber}</Text>
        <Text style={styles.meta}>Vendor Name: {vendorName}</Text>
        <Text style={styles.meta}>Purpose: {purpose}</Text>
        {amountLabel ? <Text style={styles.meta}>Amount: {amountLabel}</Text> : null}
        <Text style={{ ...styles.meta, ...(downpaymentLabel ? { color: "#b45309", fontWeight: 700 } : {}) }}>
          {downpaymentLabel
            ? `Downpayment: ${downpaymentPercent ? `${downpaymentPercent}% — ` : ""}${downpaymentLabel}`
            : "Downpayment: None"}
        </Text>
      </Section>
      <Text style={styles.paragraph}>
        Kindly review the purchase request and let me know if any revisions are
        required. If everything is in order, I would appreciate your approval at
        your earliest convenience to avoid any delay in processing.
      </Text>
      <Section style={{ margin: "8px 0 16px" }}>
        <Link href={reviewUrl} style={styles.button}>
          Review &amp; approve
        </Link>
      </Section>
    </EmailLayout>
  );
}

export default PrPendingApprovalEmail;
